/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void textfield1_change1(GTextField source, GEvent event) { //_CODE_:Hour:640672:
  println("Hour - GTextField event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:Hour:640672:

public void textfield1_change2(GTextField source, GEvent event) { //_CODE_:Minute:871063:
  println("Minute - GTextField event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:Minute:871063:

public void checkbox1_clicked1(GCheckbox source, GEvent event) { //_CODE_:SleepCheck:477023:
  println("SleepCheck - GCheckbox event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:SleepCheck:477023:

public void textarea1_change1(GTextArea source, GEvent event) { //_CODE_:Timer:318342:
  println("textarea1 - GTextArea event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:Timer:318342:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  Hour = new GTextField(this, 100, 100, 80, 22, G4P.SCROLLBARS_NONE);
  Hour.setDefaultText("Hour");
  Hour.setOpaque(true);
  Hour.addEventHandler(this, "textfield1_change1");
  Minute = new GTextField(this, 200, 100, 80, 22, G4P.SCROLLBARS_NONE);
  Minute.setDefaultText("Minute");
  Minute.setOpaque(true);
  Minute.addEventHandler(this, "textfield1_change2");
  SleepCheck = new GCheckbox(this, 100, 150, 120, 20);
  SleepCheck.setTextAlign(GAlign.LEFT, GAlign.MIDDLE);
  SleepCheck.setText("Sleep Timer");
  SleepCheck.setOpaque(false);
  SleepCheck.addEventHandler(this, "checkbox1_clicked1");
  Timer = new GTextArea(this, 100, 200, 160, 80, G4P.SCROLLBARS_NONE);
  Timer.setOpaque(true);
  Timer.addEventHandler(this, "textarea1_change1");
}

// Variable declarations 
// autogenerated do not edit
GTextField Hour; 
GTextField Minute; 
GCheckbox SleepCheck; 
GTextArea Timer; 

